'use strict'
// The built-in /privacy page (served by streamServer.js before the sign-in gate).
//
// The real page is a file (mirror-app/privacy-policy.html) that only exists in the developer's own
// checkout and is not part of the public source. When that file is absent, the route serves this
// generic notice instead of a 404, so the address works in every copy of the app and any link to it
// (a store listing, a QR code, a browser bookmark) never dead-ends. It is generated by code, loads
// nothing from anywhere else (no fonts, scripts, images or analytics) and names no person.

const POLICY_URL = 'https://www.beeboentertainment.com/movie-privacy.html'
const SECURITY_EMAIL = 'security@beeboentertainment.com'
const SUPPORT_EMAIL = 'support@beeboentertainment.com'

function privacyNoticeHtml() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy - Beebo Entertainment</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.55 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 24px 16px; background: #fff; color: #1b1b1f; }
  main { max-width: 42rem; margin: 0 auto; }
  h1 { font-size: 1.6rem; margin: 0 0 .5rem; }
  h2 { font-size: 1.1rem; margin: 1.6rem 0 .3rem; }
  a { color: #1a5fb4; }
  @media (prefers-color-scheme: dark) { body { background: #16161a; color: #e8e8ee; } a { color: #8ab4ff; } }
</style>
</head>
<body>
<main>
<h1>Privacy</h1>
<p>This is a Beebo Entertainment server: a personal media server that runs on a computer owned by the person who set it up.</p>

<h2>Where your information is kept</h2>
<p>Your library, accounts, watch history and settings are stored on the computer that hosts this server, not in a Beebo company database. The person who runs this server controls that computer and the information on it, so ask them if you have a question about your own account or history.</p>

<h2>The full privacy policy</h2>
<p>How Beebo Entertainment handles information in its apps, its website and its optional online services is described in the full policy:
<a href="${POLICY_URL}">${POLICY_URL}</a></p>

<h2>Security and privacy contact</h2>
<p>To report a security problem or ask about privacy, write to
<a href="mailto:${SECURITY_EMAIL}">${SECURITY_EMAIL}</a>. General help: <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p>
</main>
</body>
</html>
`
}

module.exports = { privacyNoticeHtml, POLICY_URL, SECURITY_EMAIL, SUPPORT_EMAIL }
