'use strict';
// ============================================================================
// secretSettings.js — secrets encrypted at rest with the OS.
// ----------------------------------------------------------------------------
// Originally the TMDB key and the email (SMTP) app password. Since security
// review #21 also: the session, media-token, upload-id and API-token HMAC
// secrets, the licence token, and the access codes (plain `code` and its
// `codeHash`) inside authUsers. They go through the same Electron safeStorage
// (DPAPI on Windows) the owner's relay secret uses.
//
// How it fits without touching every reader:
//   install() wraps THIS store's get/set/has/delete for the listed keys only, so
//   every existing `store.get('tmdbApiKey')` / `store.get('authUsers')` keeps
//   working and simply receives the decrypted value.
//
// On disk:  encryptedSettings: { tmdbApiKey: '<base64 DPAPI blob>', ...,
//                                'authUsers#fields': '<blob of {id: {code, codeHash}}>' }
//           authUsers: [ { id, name, username, ... } ]   (no code / codeHash)
//
// Migration (migrate(), run once the app is ready, and again harmlessly on
// every start): a plain-text value is encrypted, the blob is decrypted again
// and compared, and only then is the plain text removed. Nothing is deleted
// unless the encrypted copy has been proven to read back.
//
// Fallbacks, so a value is never lost:
//   - OS encryption unavailable (before app ready, a Linux box without a
//     keyring): reads return the old plain text if there is one; writes keep
//     plain text (the app has always worked that way) and migrate later.
//   - Linux's `basic_text` backend "encrypts" with a hard-coded key, which is
//     no protection at all. It is treated as unavailable, with a logged
//     warning: values stay (or go back to) plain text instead of pretending.
//   - A blob that won't decrypt (e.g. config.json copied from another PC):
//     the plain text is used if still present.
//   - A generated secret (session, token secrets) whose blob exists but can't be
//     opened right now is never overwritten on disk: a replacement would sign
//     everyone out for good. The new value is kept in memory for this run only.
//   - A downgraded app that wrote plain text again: plain text is newer, so
//     migrate() re-encrypts it over the old blob.
//
// Backups: an encrypted blob only opens on the PC that made it, so exportPlain()
// gives backup.js the real values (the backup has always carried them, and can
// be passphrase-encrypted), without the machine-bound blobs.
// ============================================================================

const ENC_KEY = 'encryptedSettings';
const DEFAULT_SECRET_KEYS = [
  'tmdbApiKey', 'emailAppPassword',
  // The owner's OpenSubtitles account (Settings > Subtitle search).
  'openSubtitlesApiKey', 'openSubtitlesPassword',
  'sessionSecret', 'mediaTokenSecret', 'uploadIdSecret', 'apiTokenSecret',
  'license.token',
];
// Secrets generated by the app itself: losing one means signing everybody out.
const GENERATED_KEYS = ['sessionSecret', 'mediaTokenSecret', 'uploadIdSecret', 'apiTokenSecret'];
// Arrays of records where only some fields are secret. Keyed by record id.
// remote / remoteLogin are the away-from-home hashes pushed to the Worker (the generated
// pass, and the member's own home password hashed for the one sign-in): a copied
// config.json must not hand them out for offline guessing either.
// webhooks: the signing secret has to be readable to sign with, so it is encrypted at rest, not hashed.
// So are the notification credentials (a Gotify token, a Pushover key, an ntfy access token).
const DEFAULT_FIELD_SECRETS = {
  authUsers: { idField: 'id', fields: ['code', 'codeHash', 'remote', 'remoteLogin', 'twoFactor', 'resetCode', 'resetTokenHash'] },
  webhooks: { idField: 'id', fields: ['secret', 'credentials'] }
};
const fieldBlobKey = (key) => key + '#fields';
// Every store key the app installs as encrypted (main.js adds the optional
// Cloudflare analytics token), plus the record arrays with encrypted fields.
// Anything reading store.store directly (streamServer's renderSettings) must
// send these through store.get, which decrypts them.
const APP_SECRET_KEYS = [...DEFAULT_SECRET_KEYS, 'cloudflareAnalyticsToken'];
const ENCRYPTED_KEY_NAMES = [...APP_SECRET_KEYS, ...Object.keys(DEFAULT_FIELD_SECRETS)];

// electron-store takes dotted keys as paths; exportPlain works on the plain object.
function getPath(obj, key) {
  let cur = obj;
  for (const part of key.split('.')) {
    if (!cur || typeof cur !== 'object') return undefined;
    cur = cur[part];
  }
  return cur;
}
function setPath(obj, key, value) {
  const parts = key.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!cur[parts[i]] || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    else cur[parts[i]] = Object.assign({}, cur[parts[i]]);
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}
function deletePath(obj, key) {
  const parts = key.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!cur[parts[i]] || typeof cur[parts[i]] !== 'object') return;
    cur[parts[i]] = Object.assign({}, cur[parts[i]]);
    cur = cur[parts[i]];
  }
  delete cur[parts[parts.length - 1]];
}

function createSecretSettings({
  store, safeStorage, keys = DEFAULT_SECRET_KEYS, fieldSecrets = DEFAULT_FIELD_SECRETS,
  generatedKeys = GENERATED_KEYS, platform = process.platform, log,
} = {}) {
  if (!store) throw new Error('store required');
  const names = new Set(keys);
  const fieldNames = new Map(Object.entries(fieldSecrets || {}));
  const generated = new Set(generatedKeys);
  // The store's own methods, before install() wraps them.
  const raw = {
    get: store.get.bind(store),
    set: store.set.bind(store),
    has: typeof store.has === 'function' ? store.has.bind(store) : (k) => raw.get(k) !== undefined,
    delete: store.delete.bind(store),
  };
  const say = (m) => { try { if (typeof log === 'function') log(m); } catch (_) {} };

  // Can we open blobs at all?
  function canDecrypt() {
    try { return !!(safeStorage && safeStorage.isEncryptionAvailable()); } catch (_) { return false; }
  }
  let warnedBasicText = false;
  function weakBackend() {
    if (platform !== 'linux' || !safeStorage || typeof safeStorage.getSelectedStorageBackend !== 'function') return false;
    let backend = '';
    try { backend = safeStorage.getSelectedStorageBackend(); } catch (_) { return false; }
    if (backend !== 'basic_text') return false;
    if (!warnedBasicText) {
      warnedBasicText = true;
      say('[secrets] WARNING: no system keyring (safeStorage backend is basic_text, a fixed built-in key); secrets are kept as plain text in config.json. Install and unlock a keyring (GNOME Keyring / KWallet) to encrypt them.');
    }
    return true;
  }
  // Is it worth encrypting with?
  function available() { return canDecrypt() && !weakBackend(); }

  function blobs() {
    const b = raw.get(ENC_KEY);
    return b && typeof b === 'object' && !Array.isArray(b) ? Object.assign({}, b) : {};
  }
  function encrypt(value) {
    const blob = safeStorage.encryptString(String(value)).toString('base64');
    // Proven to read back before anyone relies on it.
    if (safeStorage.decryptString(Buffer.from(blob, 'base64')) !== String(value)) throw new Error('round trip mismatch');
    return blob;
  }
  // The media server reads the TMDB key and the user list on many requests;
  // DPAPI is quick, but a memo of blob -> value (memory only, where the value is
  // used anyway) is quicker.
  const memo = new Map();
  function decrypt(blob) {
    if (!blob || !canDecrypt()) return undefined;
    if (memo.has(blob)) return memo.get(blob);
    try {
      const v = safeStorage.decryptString(Buffer.from(String(blob), 'base64'));
      if (memo.size > 16) memo.clear();
      memo.set(blob, v);
      return v;
    } catch (_) { return undefined; }
  }
  const isBlank = (v) => v === undefined || v === null || v === '';
  // Generated secrets we could not persist without destroying the stored one.
  const pending = new Map();

  // ---- whole-value secrets -------------------------------------------------

  function read(key) {
    if (fieldNames.has(key)) return readFields(key);
    const plain = raw.get(key);
    // Plain text present means migration hasn't happened (or can't): it is the
    // freshest value there is.
    if (!isBlank(plain)) return plain;
    const b = blobs()[key];
    const v = decrypt(b);
    if (v === undefined && b && pending.has(key)) return pending.get(key);
    return v === undefined ? plain : v;
  }

  function write(key, value) {
    if (fieldNames.has(key)) return writeFields(key, value);
    const b = blobs();
    if (isBlank(value)) {
      pending.delete(key);
      if (key in b) { delete b[key]; raw.set(ENC_KEY, b); }
      raw.delete(key);
      return;
    }
    if (available()) {
      try {
        b[key] = encrypt(value);
        raw.set(ENC_KEY, b);
        raw.delete(key);
        pending.delete(key);
        return;
      } catch (e) { say('[secrets] could not encrypt ' + key + '; keeping it as before'); }
    }
    if (generated.has(key) && b[key] && decrypt(b[key]) === undefined && isBlank(raw.get(key))) {
      // The stored secret exists but can't be opened right now (keyring locked,
      // app not ready). Replacing it would invalidate every session for good.
      pending.set(key, value);
      say('[secrets] ' + key + ' is stored encrypted but cannot be read right now; using a temporary one until restart');
      return;
    }
    // No OS encryption: keep working the way the app always has. A stale blob
    // must not shadow the new value, so drop it.
    if (key in b) { delete b[key]; raw.set(ENC_KEY, b); }
    raw.set(key, value);
  }

  function has(key) {
    if (fieldNames.has(key)) return raw.has(key);
    return !isBlank(raw.get(key)) || !!blobs()[key] || pending.has(key);
  }

  // ---- secret fields inside arrays of records (authUsers) ------------------

  function fieldMap(key) {
    const v = decrypt(blobs()[fieldBlobKey(key)]);
    if (v === undefined) return null;
    try { const m = JSON.parse(v); return m && typeof m === 'object' ? m : null; } catch (_) { return null; }
  }

  function readFields(key) {
    const list = raw.get(key);
    if (!Array.isArray(list)) return list;
    const { idField, fields } = fieldNames.get(key);
    const map = blobs()[fieldBlobKey(key)] ? fieldMap(key) : null;
    if (!map) return list;
    return list.map((rec) => {
      if (!rec || typeof rec !== 'object') return rec;
      const secret = map[rec[idField]];
      if (!secret) return rec;
      const out = Object.assign({}, rec);
      // A field still present in the plain record was written after the blob
      // (e.g. by an older app): it is the fresher value.
      for (const f of fields) if (!(f in rec) && f in secret) out[f] = secret[f];
      return out;
    });
  }

  function hasPlainFields(list, key) {
    const { idField, fields } = fieldNames.get(key);
    return Array.isArray(list) && list.some((r) => r && typeof r === 'object' && r[idField] !== undefined && fields.some((f) => f in r));
  }

  function writeFields(key, value) {
    const b = blobs();
    const bk = fieldBlobKey(key);
    if (!Array.isArray(value) || !available()) {
      if (bk in b && (!Array.isArray(value) || !hasBlobOnlyRecords(key, value))) { delete b[bk]; raw.set(ENC_KEY, b); }
      raw.set(key, value);
      return;
    }
    const { idField, fields } = fieldNames.get(key);
    const map = {};
    const stripped = value.map((rec) => {
      if (!rec || typeof rec !== 'object' || rec[idField] === undefined) return rec;
      const secret = {};
      const rest = Object.assign({}, rec);
      for (const f of fields) if (f in rec) { secret[f] = rec[f]; delete rest[f]; }
      map[rec[idField]] = secret;
      return rest;
    });
    try {
      const json = JSON.stringify(map);
      b[bk] = encrypt(json);
      raw.set(ENC_KEY, b);
      // Read it back through the store before the plain fields go.
      if (decrypt(blobs()[bk]) !== json) throw new Error('verify failed');
      raw.set(key, stripped);
    } catch (e) {
      say('[secrets] could not encrypt ' + key + ' fields; keeping them as before');
      raw.set(key, value);
    }
  }

  // Would dropping the blob lose a record's secret fields? (No OS encryption
  // now, but records written earlier only have them in the blob.)
  function hasBlobOnlyRecords(key, list) {
    const { idField, fields } = fieldNames.get(key);
    return list.some((r) => r && typeof r === 'object' && r[idField] !== undefined && !fields.every((f) => f in r));
  }

  // ---- migration -----------------------------------------------------------

  // Encrypt any plain-text secrets. Returns { migrated: [...], kept: [...] }.
  function migrate() {
    const out = { migrated: [], kept: [] };
    const strong = available();
    if (!strong && canDecrypt()) unmigrateWeak(out);
    for (const key of names) {
      const plain = raw.get(key);
      if (isBlank(plain)) continue;
      if (!strong) { out.kept.push(key); continue; }
      try {
        const b = blobs();
        b[key] = encrypt(plain);
        raw.set(ENC_KEY, b);
        // Read it back through the store (what every later reader does) before
        // letting go of the plain text.
        if (decrypt(blobs()[key]) !== String(plain)) throw new Error('verify failed');
        raw.delete(key);
        out.migrated.push(key);
      } catch (e) {
        out.kept.push(key);
        say('[secrets] ' + key + ' left as it was (could not encrypt it)');
      }
    }
    for (const key of fieldNames.keys()) {
      const list = raw.get(key);
      if (!hasPlainFields(list, key)) continue;
      if (!strong) { out.kept.push(key); continue; }
      const merged = readFields(key);
      writeFields(key, merged);
      if (hasPlainFields(raw.get(key), key)) out.kept.push(key); else out.migrated.push(key);
    }
    if (out.migrated.length) say('[secrets] encrypted with the OS: ' + out.migrated.join(', '));
    return out;
  }

  // basic_text (Linux without a keyring): blobs made that way protect nothing.
  // Put the values back as plain text, each verified before its blob goes.
  function unmigrateWeak(out) {
    const b = blobs();
    let changed = false;
    for (const key of names) {
      if (!b[key]) continue;
      const v = decrypt(b[key]);
      if (v === undefined) continue;
      if (isBlank(raw.get(key))) raw.set(key, v);
      if (raw.get(key) === undefined) continue;
      delete b[key];
      changed = true;
      out.kept.push(key);
    }
    for (const key of fieldNames.keys()) {
      const bk = fieldBlobKey(key);
      if (!b[bk]) continue;
      const merged = readFields(key);
      if (!Array.isArray(merged)) continue;
      raw.set(key, merged);
      delete b[bk];
      changed = true;
      out.kept.push(key);
    }
    if (changed) raw.set(ENC_KEY, b);
  }

  // ---- install -------------------------------------------------------------

  // Top-level key whose object value contains a dotted secret (e.g. 'license'
  // holding 'license.token'), as a backup restore writes it.
  function nestedSecretsUnder(key) {
    const found = [];
    for (const name of names) if (name.startsWith(key + '.')) found.push(name);
    return found;
  }

  function install() {
    if (store.__beeboSecretsInstalled) return api;
    store.get = (key, def) => {
      if (typeof key === 'string' && (names.has(key) || fieldNames.has(key))) {
        const v = read(key);
        return v === undefined ? def : v;
      }
      return raw.get(key, def);
    };
    store.set = (key, value) => {
      if (key && typeof key === 'object') {
        for (const [k, v] of Object.entries(key)) store.set(k, v);
        return;
      }
      if (typeof key === 'string' && (names.has(key) || fieldNames.has(key))) return write(key, value);
      if (typeof key === 'string' && value && typeof value === 'object' && !Array.isArray(value)) {
        const nested = nestedSecretsUnder(key);
        if (nested.length) {
          const rest = JSON.parse(JSON.stringify(value));
          const secrets = [];
          for (const name of nested) {
            const sub = name.slice(key.length + 1);
            const v = getPath(rest, sub);
            if (v !== undefined) { secrets.push([name, v]); deletePath(rest, sub); }
          }
          raw.set(key, rest);
          for (const [name, v] of secrets) write(name, v);
          return;
        }
      }
      return raw.set(key, value);
    };
    store.has = (key) => (typeof key === 'string' && (names.has(key) || fieldNames.has(key)) ? has(key) : raw.has(key));
    store.delete = (key) => {
      if (typeof key === 'string' && names.has(key)) return write(key, '');
      if (typeof key === 'string' && fieldNames.has(key)) {
        const b = blobs();
        if (fieldBlobKey(key) in b) { delete b[fieldBlobKey(key)]; raw.set(ENC_KEY, b); }
        return raw.delete(key);
      }
      return raw.delete(key);
    };
    // Backups need values that open on another PC.
    store.exportPlain = () => exportPlain();
    Object.defineProperty(store, '__beeboSecretsInstalled', { value: true, enumerable: false });
    return api;
  }

  // The whole store as backup.js should save it: real values, no blobs.
  function exportPlain() {
    const all = Object.assign({}, store.store);
    delete all[ENC_KEY];
    for (const key of names) {
      const v = read(key);
      if (key.includes('.')) {
        if (isBlank(v)) deletePath(all, key); else setPath(all, key, v);
      } else if (isBlank(v)) delete all[key]; else all[key] = v;
    }
    for (const key of fieldNames.keys()) {
      const v = read(key);
      if (v !== undefined) all[key] = v;
    }
    return all;
  }

  const api = { install, migrate, read, write, has, exportPlain, available, ENC_KEY };
  return api;
}

module.exports = { createSecretSettings, DEFAULT_SECRET_KEYS, APP_SECRET_KEYS, ENCRYPTED_KEY_NAMES, DEFAULT_FIELD_SECRETS, GENERATED_KEYS, ENC_KEY };
