import React, { useState, useMemo } from 'react'
import licenses from '../open-source-licenses.json'

// Self-contained "Open Source Licenses" screen. Renders as a full-window modal
// overlay so it can be dropped in from anywhere with a single <OpenSourceLicenses
// onClose={...} /> and no other wiring. Data comes from open-source-licenses.json,
// which is regenerated by the license inventory script.

const C = {
  overlay: 'rgba(0,0,0,0.72)',
  panel: '#1b1d21',
  panelBorder: '#2c2f36',
  head: '#0f1013',
  text: '#e7e9ee',
  dim: 'var(--muted)',
  accent: '#f5c542',
  chip: '#26303b',
  chipText: '#9ecbff',
  codeBg: '#111317',
}

function licenseColor(l) {
  if (/GPL/.test(l) && !/LGPL/.test(l)) return '#ff8f8f'
  if (/LGPL|MPL/.test(l)) return '#ffd479'
  return C.chipText
}

export default function OpenSourceLicenses({ onClose }) {
  const [query, setQuery] = useState('')
  const [openName, setOpenName] = useState(null)

  const list = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return licenses
    return licenses.filter(
      (r) =>
        r.name.toLowerCase().includes(q) ||
        (r.license || '').toLowerCase().includes(q)
    )
  }, [query])

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, background: C.overlay, zIndex: 9999,
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24,
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          width: 'min(860px, 100%)', maxHeight: '90vh', display: 'flex',
          flexDirection: 'column', background: C.panel, color: C.text,
          border: `1px solid ${C.panelBorder}`, borderRadius: 12, overflow: 'hidden',
          boxShadow: '0 20px 60px rgba(0,0,0,0.5)', fontFamily: 'Segoe UI, system-ui, sans-serif',
        }}
      >
        {/* header */}
        <div style={{ background: C.head, padding: '18px 22px', borderBottom: `1px solid ${C.panelBorder}` }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div>
              <div style={{ fontSize: 18, fontWeight: 700 }}>Open Source Licenses</div>
              <div style={{ fontSize: 12, color: C.dim, marginTop: 2 }}>
                Beebo Entertainment is built with the open-source software below. Thank you to its authors.
              </div>
            </div>
            <button
              onClick={onClose}
              style={{
                background: 'transparent', color: C.dim, border: 'none', fontSize: 22,
                cursor: 'pointer', lineHeight: 1, padding: 4,
              }}
              title="Close"
            >
              ×
            </button>
          </div>
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={`Search ${licenses.length} components…`}
            style={{
              marginTop: 12, width: '100%', boxSizing: 'border-box', padding: '9px 12px',
              background: C.codeBg, color: C.text, border: `1px solid ${C.panelBorder}`,
              borderRadius: 8, fontSize: 13, outline: 'none',
            }}
          />
        </div>

        {/* list */}
        <div style={{ overflowY: 'auto', padding: '8px 12px 16px' }}>
          {list.length === 0 && (
            <div style={{ color: C.dim, padding: 20, textAlign: 'center' }}>No matches.</div>
          )}
          {list.map((r) => {
            const isOpen = openName === r.name
            return (
              <div
                key={r.name}
                style={{
                  border: `1px solid ${C.panelBorder}`, borderRadius: 8, marginTop: 8,
                  background: '#202329', overflow: 'hidden',
                }}
              >
                <button
                  onClick={() => setOpenName(isOpen ? null : r.name)}
                  style={{
                    width: '100%', textAlign: 'left', background: 'transparent', border: 'none',
                    color: C.text, cursor: 'pointer', padding: '11px 14px', display: 'flex',
                    alignItems: 'center', gap: 10,
                  }}
                >
                  <span style={{ color: C.dim, fontSize: 12, width: 12 }}>{isOpen ? '▾' : '▸'}</span>
                  <span style={{ fontWeight: 600, fontSize: 14 }}>{r.name}</span>
                  <span style={{ color: C.dim, fontSize: 12 }}>{r.version}</span>
                  <span
                    style={{
                      marginLeft: 'auto', fontSize: 11, fontWeight: 600, padding: '3px 8px',
                      borderRadius: 20, background: C.chip, color: licenseColor(r.license),
                      whiteSpace: 'nowrap',
                    }}
                  >
                    {r.license}
                  </span>
                </button>
                {isOpen && (
                  <div style={{ padding: '0 14px 14px', borderTop: `1px solid ${C.panelBorder}` }}>
                    {r.homepage && (
                      <div style={{ fontSize: 12, marginTop: 10 }}>
                        <span style={{ color: C.dim }}>Homepage: </span>
                        <a
                          href={r.homepage}
                          target="_blank"
                          rel="noreferrer"
                          style={{ color: C.chipText }}
                        >
                          {r.homepage}
                        </a>
                      </div>
                    )}
                    {r.note && (
                      <div style={{ fontSize: 12, color: C.dim, marginTop: 8, lineHeight: 1.5 }}>{r.note}</div>
                    )}
                    <pre
                      style={{
                        marginTop: 10, marginBottom: 0, maxHeight: 320, overflow: 'auto',
                        background: C.codeBg, border: `1px solid ${C.panelBorder}`, borderRadius: 6,
                        padding: 12, fontSize: 11.5, lineHeight: 1.5, color: '#c8ccd4',
                        whiteSpace: 'pre-wrap', wordBreak: 'break-word',
                        fontFamily: 'Consolas, Menlo, monospace',
                      }}
                    >
                      {r.text || `Distributed under the ${r.license} license.`}
                    </pre>
                  </div>
                )}
              </div>
            )
          })}
        </div>

        {/* footer */}
        <div
          style={{
            background: C.head, padding: '10px 22px', borderTop: `1px solid ${C.panelBorder}`,
            fontSize: 11, color: C.dim, display: 'flex', justifyContent: 'space-between',
          }}
        >
          <span>{licenses.length} open-source components</span>
          <span>Full texts also in the app's THIRD_PARTY_LICENSES folder</span>
        </div>
      </div>
    </div>
  )
}
