// The mini-player's pure logic (src/lib/audioPlayer.js): variable speed 0.5x-3x, the sleep timer,
// chapter navigation and the shared now-playing store. No React, no network.
// Run: node --test test/audio-player.test.js
const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const { pathToFileURL } = require('node:url')
const appRoot = path.resolve(__dirname, '..')
const load = () => import(pathToFileURL(path.join(appRoot, 'src', 'lib', 'audioPlayer.js')).href)

test('speed: clamped to 0.5x-3x in 0.05 steps, stepping through the usual presets, and it matches the server', async () => {
  const P = await load()
  assert.equal(P.clampSpeed(1.5), 1.5)
  assert.equal(P.clampSpeed('2.25'), 2.25)
  assert.equal(P.clampSpeed(0.2), 0.5)
  assert.equal(P.clampSpeed(7), 3)
  assert.equal(P.clampSpeed(1.234), 1.25)
  assert.equal(P.clampSpeed('fast', 1.25), 1.25)
  assert.equal(P.stepSpeed(1, +1), 1.25)
  assert.equal(P.stepSpeed(1.3, +1), 1.5)
  assert.equal(P.stepSpeed(1, -1), 0.75)
  assert.equal(P.stepSpeed(3, +1), 3)
  assert.equal(P.stepSpeed(0.5, -1), 0.5)
  assert.equal(P.stepSpeed(2, +1), 2.5)
  assert.equal(P.formatSpeed(1.5), '1.5x')
  // one rule for the desktop and the server
  const server = require(path.join(appRoot, 'electron', 'podcastService.js'))
  for (const v of [0, 0.5, 0.74, 1, 1.01, 1.337, 2.999, 3, 3.01, 'x', NaN, -1]) assert.equal(P.clampSpeed(v), server.clampSpeed(v), String(v))
  assert.equal(P.SPEED_MIN, server.SPEED_MIN)
  assert.equal(P.SPEED_MAX, server.SPEED_MAX)
})

test('clock and time left: at 2x an hour takes half an hour', async () => {
  const P = await load()
  assert.equal(P.formatClock(3723), '1:02:03')
  assert.equal(P.formatClock(65), '1:05')
  assert.equal(P.formatClock(-4), '0:00')
  assert.equal(P.formatClock('junk'), '0:00')
  assert.equal(P.timeLeft(0, 3600, 2), 1800)
  assert.equal(P.timeLeft(3000, 3600, 1), 600)
  assert.equal(P.timeLeft(0, 0, 1), 0)
  assert.equal(P.timeLeft(4000, 3600, 1), 0)
})

test('sleep timer: minutes count down and fire; "end of episode" waits for the end; bad input makes none', async () => {
  const P = await load()
  const t0 = 1_000_000
  const timer = P.startSleepTimer(15, t0)
  assert.deepEqual(timer, { mode: 'minutes', endsAt: t0 + 15 * 60000 })
  assert.equal(P.sleepRemaining(timer, t0), 900)
  assert.equal(P.sleepRemaining(timer, t0 + 899_500), 1)
  assert.equal(P.sleepShouldStop(timer, { now: t0 + 899_000 }), false)
  assert.equal(P.sleepShouldStop(timer, { now: t0 + 900_000 }), true)
  assert.equal(P.sleepRemaining(timer, t0 + 2_000_000), 0)
  assert.equal(P.sleepLabel(timer, t0), 'Stops in 15:00')
  const ep = P.startSleepTimer('episode')
  assert.deepEqual(ep, { mode: 'episode' })
  assert.equal(P.sleepShouldStop(ep, { now: t0 + 1e9, ended: false }), false, 'time alone never stops an end-of-episode timer')
  assert.equal(P.sleepShouldStop(ep, { ended: true }), true)
  assert.equal(P.sleepRemaining(ep), null)
  assert.equal(P.sleepLabel(ep), 'Stops after this episode')
  for (const bad of [0, -5, 'abc', 100000, NaN, null]) assert.equal(P.startSleepTimer(bad, t0), null, String(bad))
  assert.equal(P.sleepShouldStop(null), false)
  assert.equal(P.sleepLabel(null), 'Sleep timer')
})

test('chapters: which is playing, next, previous (restart first), hidden ones skipped', async () => {
  const P = await load()
  const ch = [
    { start: 0, title: 'Intro' },
    { start: 60, title: 'Ad break', hidden: true },
    { start: 120, title: 'Main topic' },
    { start: 900, title: 'Wrap-up' }
  ]
  assert.deepEqual(P.visibleChapters(ch).map((c) => c.title), ['Intro', 'Main topic', 'Wrap-up'])
  assert.equal(P.chapterAt(ch, 0).title, 'Intro')
  assert.equal(P.chapterAt(ch, 100).title, 'Intro', 'a hidden chapter does not become the current one')
  assert.equal(P.chapterAt(ch, 120).title, 'Main topic')
  assert.equal(P.chapterAt(ch, 119.9).title, 'Main topic', 'a hair before the mark counts as the chapter that is starting')
  assert.equal(P.chapterAt(ch, 5000).title, 'Wrap-up')
  assert.equal(P.chapterAt([{ start: 30, title: 'Late start' }], 10), null, 'before the first chapter')
  assert.equal(P.chapterAt([], 10), null)
  assert.equal(P.chapterAt(null, 10), null)
  assert.equal(P.nextChapterStart(ch, 10), 120)
  assert.equal(P.nextChapterStart(ch, 1000), null)
  assert.equal(P.prevChapterStart(ch, 130), 120, 'past the first seconds: back to this chapter start')
  assert.equal(P.prevChapterStart(ch, 121), 0, 'right at the start: the one before')
  assert.equal(P.prevChapterStart(ch, 1), 0)
  assert.equal(P.prevChapterStart([{ start: 30, title: 'x' }], 5), 0)
})

test('the shared store: play, patch, subscribe, stop; speed and skip-silence survive a stop', async () => {
  const P = await load()
  const seen = []
  const off = P.subscribe((s) => seen.push(s.item ? s.item.title : null))
  assert.equal(P.getPlayback().item, null)
  P.play({ kind: 'podcast', key: 'k', title: 'Ep 1', stream: 'http://x/y', progressSec: 42, durationSec: 3000 })
  assert.equal(P.getPlayback().item.title, 'Ep 1')
  assert.equal(P.getPlayback().position, 42)
  assert.equal(P.getPlayback().duration, 3000)
  P.patchPlayback({ speed: 1.75, skipSilence: true, sleep: P.startSleepTimer(10, 0) })
  P.play({ kind: 'radio', sessionId: 's', title: 'Test FM', stream: 'http://x/live' })
  assert.equal(P.getPlayback().speed, 1.75, 'speed carries over to the next thing')
  assert.equal(P.getPlayback().position, 0)
  P.play({ kind: 'radio', title: 'no stream address' })
  P.play({ kind: 'movie', stream: 'x' })
  P.play(null)
  assert.equal(P.getPlayback().item.title, 'Test FM', 'nothing invalid replaces what is playing')
  P.stop()
  assert.equal(P.getPlayback().item, null)
  assert.equal(P.getPlayback().speed, 1.75)
  assert.equal(P.getPlayback().skipSilence, true)
  assert.equal(P.getPlayback().sleep, null, 'a stop clears the sleep timer')
  off()
  P.patchPlayback({ note: 'after unsubscribe' })
  assert.deepEqual(seen.slice(0, 3), ['Ep 1', 'Ep 1', 'Test FM'])
  assert.equal(seen[seen.length - 1], null)
  assert.ok(!seen.includes('after unsubscribe'))
})
