package com.beeboentertainment.movie.campsite.games

/**
 * The prompts for Fake Out: a true fact with its answer blanked, written in our own words
 * for this app. Every one is a well-documented fact, kept to things that are safe and
 * pleasant to read aloud in any company.
 *
 * [kind] groups answers of the same shape (a number, a place, a word...). It is only used
 * to find a believable decoy when too few players wrote a fake: another fact's answer of
 * the same kind reads like a real option without being this fact's answer.
 */
internal data class FakeOutFact(val prompt: String, val answer: String, val kind: String)

internal object FakeOutFacts {
    private fun f(prompt: String, answer: String, kind: String) = FakeOutFact(prompt, answer, kind)

    val ALL: List<FakeOutFact> = listOf(
        // ---- words for groups and young animals ----
        f("A group of flamingos is called a ____.", "flamboyance", "word"),
        f("A group of owls is called a ____.", "parliament", "word"),
        f("A group of porcupines is called a ____.", "prickle", "word"),
        f("A group of jellyfish is called a ____.", "smack", "word"),
        f("A group of rhinos is called a ____.", "crash", "word"),
        f("A group of zebras is called a ____.", "dazzle", "word"),
        f("A group of hippos is called a ____.", "bloat", "word"),
        f("A group of ferrets is called a ____.", "business", "word"),
        f("A baby puffin is called a ____.", "puffling", "word"),
        f("A baby hedgehog is called a ____.", "hoglet", "word"),
        f("A baby platypus is often called a ____.", "puggle", "word"),
        f("A male honeybee is called a ____.", "drone", "word"),
        // ---- animals ----
        f("Wombats are famous for leaving droppings shaped like ____.", "cubes", "thing"),
        f("An octopus has this many hearts: ____.", "three", "number"),
        f("Sea otters often hold ____ while they sleep so they don't drift apart.", "paws", "body"),
        f("A shrimp's heart is found in its ____.", "head", "body"),
        f("A cow's stomach has this many compartments: ____.", "four", "number"),
        f("The fingerprints of the ____ are so like ours they are hard to tell apart.", "koala", "animal"),
        f("A giraffe's tongue is usually this colour: ____.", "purple", "colour"),
        f("Butterflies taste with their ____.", "feet", "body"),
        f("Honeybees tell each other where flowers are by doing a ____.", "dance", "thing"),
        f("The national animal of Scotland is the ____.", "unicorn", "animal"),
        f("A hinny is the young of a male horse and a female ____.", "donkey", "animal"),
        f("Under all that white fur, a polar bear's skin is ____.", "black", "colour"),
        f("The only mammal that can truly fly is the ____.", "bat", "animal"),
        f("An ostrich's eye is bigger than its ____.", "brain", "body"),
        f("Hummingbirds are the only birds that can fly ____.", "backwards", "thing"),
        f("The axolotl, a Mexican salamander, can regrow lost ____.", "limbs", "body"),
        f("A sloth can hold its breath for longer than most ____.", "dolphins", "animal"),
        f("In seahorses, it is the ____ who carries the babies.", "father", "person"),
        f("A woodpecker's ____ wraps around the back of its skull.", "tongue", "body"),
        f("Snakes smell with their ____.", "tongues", "body"),
        f("A cat has this many muscles in each ear: ____.", "32", "number"),
        f("Dolphins sleep with one ____ open.", "eye", "body"),
        f("Scientists found that rats make laughing sounds when they are ____.", "tickled", "thing"),
        f("Goats have pupils shaped like ____.", "rectangles", "thing"),
        f("A newborn giraffe can usually stand within about an ____.", "hour", "time"),
        f("Ants breathe without having any ____.", "lungs", "body"),
        f("A chameleon's tongue can be longer than its ____.", "body", "body"),
        f("Arctic terns fly between the Arctic and the ____ every year.", "Antarctic", "place"),
        f("A gentoo penguin courts its mate by offering a ____.", "pebble", "thing"),
        f("By forgetting where they buried seeds, squirrels accidentally plant ____.", "trees", "thing"),
        f("Sharks have been around for longer than ____.", "trees", "thing"),
        f("Humans and giraffes have the same number of neck bones: ____.", "seven", "number"),
        // ---- food ----
        f("Honey found in ancient Egyptian tombs was still ____.", "edible", "thing"),
        f("Botanically speaking, bananas are ____.", "berries", "food"),
        f("Peanuts are not really nuts - they are ____.", "legumes", "food"),
        f("A pineapple plant takes about this long to grow one fruit: ____.", "two years", "time"),
        f("The first cultivated carrots were not orange - they were mostly ____.", "purple", "colour"),
        f("Almond trees belong to the same plant family as the ____.", "rose", "food"),
        f("In the 1830s, tomato ketchup was sold in America as a ____.", "medicine", "thing"),
        f("By weight, the most expensive spice in the world is ____.", "saffron", "food"),
        f("Apples float because about a quarter of an apple is ____.", "air", "thing"),
        f("A cashew nut grows on the bottom of a fruit called the cashew ____.", "apple", "food"),
        f("Broccoli, cabbage, kale and cauliflower are all the same plant ____.", "species", "word"),
        f("The ice pop on a stick was invented by accident by a boy aged ____.", "eleven", "number"),
        f("When tomatoes first reached Europe, some people called them poison ____.", "apples", "food"),
        f("Chocolate chip cookies were invented in this decade: the ____.", "1930s", "year"),
        f("A single piece of spaghetti is properly called a ____.", "spaghetto", "food"),
        f("The kiwi fruit used to be sold as the Chinese ____.", "gooseberry", "food"),
        f("The microwave oven was discovered when a ____ melted in an engineer's pocket.", "chocolate bar", "food"),
        f("Before rubber erasers, people rubbed out pencil marks with ____.", "bread", "food"),
        // ---- words and language ----
        f("The dot over a lowercase i is called a ____.", "tittle", "word"),
        f("The plastic tip on the end of a shoelace is called an ____.", "aglet", "word"),
        f("An official name for the # symbol is the ____.", "octothorpe", "word"),
        f("The groove between your nose and your upper lip is called the ____.", "philtrum", "word"),
        f("The tiny pocket inside the front pocket of jeans was made for ____.", "pocket watches", "thing"),
        f("A jiffy is a real unit of ____.", "time", "word"),
        f("The word robot comes from a Czech word meaning ____.", "forced labor", "word"),
        f("An old word for a person who always wants the latest gossip is a ____.", "quidnunc", "word"),
        f("The word muscle comes from the Latin for little ____.", "mouse", "animal"),
        f("A sentence that uses every letter of the alphabet is called a ____.", "pangram", "word"),
        f("The earthy smell after rain on dry ground is called ____.", "petrichor", "word"),
        f("An old English word for the day after tomorrow is ____.", "overmorrow", "word"),
        f("A medieval moment was a unit of time lasting ____ seconds.", "90", "number"),
        f("The chess piece called the rook takes its name from a Persian word for ____.", "chariot", "thing"),
        f("The only letter that does not appear in any US state name is ____.", "Q", "word"),
        f("Researchers counted more than 400 Scots words for ____.", "snow", "thing"),
        f("The name Wendy became popular thanks to the story ____.", "Peter Pan", "person"),
        f("Denim jeans take their name from the Italian city of ____.", "Genoa", "place"),
        // ---- places ----
        f("The only national flag that is not a rectangle or square belongs to ____.", "Nepal", "place"),
        f("The country with the most islands is usually said to be ____.", "Sweden", "place"),
        f("The world's shortest scheduled passenger flight, under two minutes, is in ____.", "Scotland", "place"),
        f("Australia is wider from east to west than the ____.", "moon", "thing"),
        f("Canada has more ____ than the rest of the world put together.", "lakes", "thing"),
        f("Russia stretches across this many time zones: ____.", "eleven", "number"),
        f("There is a village in Norway called ____.", "Hell", "place"),
        f("The Eiffel Tower grows a few centimetres taller in ____.", "summer", "time"),
        f("Because its islands cross 180 degrees longitude, Alaska is the westernmost and also the ____ US state.", "easternmost", "word"),
        f("Canada's national summer sport is ____.", "lacrosse", "thing"),
        f("The city of Istanbul sits on two ____.", "continents", "thing"),
        f("The national symbol on Irish coins is a ____.", "harp", "thing"),
        f("The burning gas crater known as the Door to Hell is in ____.", "Turkmenistan", "place"),
        f("The driest non-polar desert on Earth is the ____.", "Atacama", "place"),
        f("Lake Baikal in Russia is the world's ____ lake.", "deepest", "word"),
        f("The largest desert in the world is ____.", "Antarctica", "place"),
        f("Measured from the centre of the Earth, the highest mountain peak is ____.", "Chimborazo", "place"),
        f("The river that crosses the equator twice is the ____.", "Congo", "place"),
        f("The only two doubly landlocked countries are Liechtenstein and ____.", "Uzbekistan", "place"),
        f("The world's tallest waterfall, Angel Falls, is in ____.", "Venezuela", "place"),
        f("One of the few places in the world with no mosquitoes is ____.", "Iceland", "place"),
        f("The Canary Islands are named after ____.", "dogs", "animal"),
        f("The Ring of Fire, full of volcanoes, circles the ____ Ocean.", "Pacific", "place"),
        f("Some of the oldest living trees on Earth are bristlecone ____.", "pines", "thing"),
        // ---- space ----
        f("The Sea of Tranquility is on the ____.", "moon", "thing"),
        f("A single day on Venus lasts longer than a ____ on Venus.", "year", "time"),
        f("Saturn is light enough that it would ____ in a big enough bath.", "float", "thing"),
        f("The largest volcano in the solar system, Olympus Mons, is on ____.", "Mars", "place"),
        f("Sunsets on Mars look ____.", "blue", "colour"),
        f("There are more trees on Earth than ____ in the Milky Way.", "stars", "thing"),
        f("Sunlight takes about this many minutes to reach Earth: ____.", "eight", "number"),
        f("The hottest planet in our solar system is ____.", "Venus", "place"),
        f("Uranus spins lying on its ____.", "side", "thing"),
        f("A day on Jupiter lasts about this many hours: ____.", "ten", "number"),
        f("A bolt of lightning is about this many times hotter than the surface of the Sun: ____.", "five", "number"),
        f("A fluffy cumulus cloud can weigh more than a million ____.", "pounds", "thing"),
        f("Under the right conditions hot water can freeze faster than cold, which is called the ____ effect.", "Mpemba", "person"),
        // ---- the human body ----
        f("The smallest bone in the human body is in the ____.", "ear", "body"),
        f("Babies are born with about 300 ____; adults have 206.", "bones", "body"),
        f("Measured by force, one of the strongest muscles in the body is in the ____.", "jaw", "body"),
        f("Fingernails grow faster than ____.", "toenails", "body"),
        f("The part of the body with no blood supply of its own is the ____.", "cornea", "body"),
        f("You can't hum while you hold your ____.", "nose", "body"),
        f("The tallest person on record was 8 feet 11 inches tall and named Robert ____.", "Wadlow", "person"),
        f("The longest recorded bout of hiccups lasted ____ years.", "68", "number"),
        // ---- history and inventions ----
        f("The first product ever scanned with a barcode was a pack of ____.", "chewing gum", "food"),
        f("Bubble wrap was first invented to be used as ____.", "wallpaper", "thing"),
        f("The first American alarm clock could only ring at ____.", "4 a.m.", "time"),
        f("The University of Oxford is older than the ____ Empire.", "Aztec", "place"),
        f("Cleopatra lived closer in time to the Moon landing than to the building of the Great ____.", "Pyramid", "thing"),
        f("The shortest war in history, between Britain and Zanzibar, lasted less than an ____.", "hour", "time"),
        f("Napoleon was once chased off at a hunting party by a crowd of ____.", "rabbits", "animal"),
        f("The first driver convicted of speeding, in 1896, was going about this many miles per hour: ____.", "eight", "number"),
        f("The cigarette lighter was invented a few years before the friction ____.", "match", "thing"),
        f("In ancient Greece, tossing an ____ to someone could be a declaration of love.", "apple", "food"),
        f("Olympic gold medals are made mostly of ____.", "silver", "thing"),
        f("The world's first webcam was pointed at a ____.", "coffee pot", "thing"),
        f("The first computer bug ever logged was a real ____.", "moth", "animal"),
        f("The Hundred Years' War actually lasted ____ years.", "116", "number"),
        f("Until 1752, the new year in England officially began in ____.", "March", "time"),
        f("In the Mona Lisa, the woman has no visible ____.", "eyebrows", "body"),
        f("A standard piano has this many keys: ____.", "88", "number"),
        f("The Eiffel Tower was originally only meant to stand for ____ years.", "twenty", "number"),
        f("Beethoven wrote some of his greatest music after he became ____.", "deaf", "thing"),
        f("In Switzerland it is against the law to keep just one ____.", "guinea pig", "animal"),
        f("Bamboo can grow almost a metre in a single ____.", "day", "time"),
        f("A baker's dozen is this many: ____.", "thirteen", "number"),
        f("The letter most recently added to the English alphabet was ____.", "J", "word"),
        f("The full name of the Statue of Liberty is Liberty Enlightening the ____.", "World", "thing"),
        f("Building the Leaning Tower of Pisa took almost this many years: ____.", "200", "number"),
    )
}
