package com.beeboentertainment.movie.campsite.games

/**
 * Hot Potato categories. Each is something a player can answer out loud in a couple of
 * seconds, with enough answers that a circle of ten can go round a few times. Written
 * for Beebo; family-friendly and for a general audience.
 */
internal object HotPotatoContent {

    val CATEGORIES: List<String> = listOf(
        // Outdoors and camping
        "Things at a campsite",
        "Things you pack for a camping trip",
        "Things you can roast on a fire",
        "Things you find on a beach",
        "Things you find in a forest",
        "Things that live in a pond",
        "Animals that fly",
        "Animals that swim",
        "Animals that hop or jump",
        "Animals with stripes or spots",
        "Animals that come out at night",
        "Birds",
        "Insects and bugs",
        "Trees",
        "Flowers",
        "Things that grow in a garden",
        "Kinds of weather",
        "Things in the night sky",
        "Things that glow",
        "Things with a tail",
        "Things you might see on a hike",
        "Things made of wood",
        "Things you can climb",
        "Things that float",
        "Things that are sticky",
        "Things that are prickly or sharp",
        "Things that make a buzzing sound",
        "Mountains, hills or volcanoes you can name",
        "Rivers or lakes you can name",
        "Types of boat",
        // Food and drink
        "Fruits",
        "Vegetables",
        "Pizza toppings",
        "Sandwich fillings",
        "Breakfast foods",
        "Things you eat with a spoon",
        "Snacks",
        "Desserts",
        "Ice cream flavours",
        "Cheeses",
        "Things you put on toast",
        "Drinks",
        "Soups",
        "Kinds of bread",
        "Crunchy foods",
        "Foods that are round",
        "Things in a lunchbox",
        "Things found in a kitchen",
        "Herbs and spices",
        "Foods that are yellow",
        "Foods that are red",
        "Foods that start with P",
        "Foods from Italy",
        "Things you can bake",
        "Things you cook on a barbecue",
        "Nuts and seeds",
        "Things you can put in a smoothie",
        "Things in a picnic basket",
        "Kinds of pasta",
        "Things on a restaurant menu",
        // Around the house
        "Things in a bathroom",
        "Things in a bedroom",
        "Things with a plug",
        "Things with buttons",
        "Things with wheels",
        "Things that open and close",
        "Things that are soft",
        "Things that are cold",
        "Things that are hot",
        "Things that make noise",
        "Things you can fold",
        "Things with a lid",
        "Things with handles",
        "Things in a toolbox",
        "Things in a junk drawer",
        "Things you clean with",
        "Furniture",
        "Things with a screen",
        "Things that use batteries",
        "Things you find in a garage",
        "Things you can plug headphones into",
        "Things that tick or beep",
        "Things you keep in a wallet or purse",
        "Things in a first aid kit",
        "Things in a school bag",
        "Things that come in pairs",
        "Things that are square",
        "Things that are round",
        "Things that are shiny",
        "Things made of glass",
        "Things made of metal",
        "Things made of paper",
        "Things made of plastic",
        "Things that stretch",
        "Things that bounce",
        "Things that spin",
        "Things you can pour",
        "Things you can stack",
        "Things that can break",
        "Things you can wear on your head",
        // Clothing and people
        "Things you wear on your feet",
        "Things you wear when it's cold",
        "Things you wear at the beach",
        "Colours",
        "Jobs",
        "Jobs that use a uniform",
        "People who help you",
        "Family members",
        "Names that start with M",
        "Names that start with J",
        "Things a doctor uses",
        "Things a chef uses",
        "Things an artist uses",
        "Things a builder uses",
        "Things a farmer has",
        "Things you find in a hospital",
        "Things you find in a library",
        "Things you find in a supermarket",
        "Things you find at an airport",
        "Things you find at a fair or carnival",
        // Sport, games and hobbies
        "Sports",
        "Sports with a ball",
        "Things you need for a sport",
        "Board games",
        "Card games",
        "Playground games",
        "Hobbies",
        "Musical instruments",
        "Dance styles",
        "Things you can collect",
        "Things you do in the snow",
        "Things you do at the pool",
        "Olympic events",
        "Things you can race",
        "Things you can throw",
        "Things you can kick",
        "Martial arts",
        "Arts and crafts supplies",
        "Things you can draw with",
        "Things at a birthday party",
        // Places and travel
        "Countries",
        "Capital cities",
        "Countries in Europe",
        "Countries in Asia",
        "Countries in Africa",
        "Countries in the Americas",
        "Cities you'd like to visit",
        "Places you can go on holiday",
        "Things you see at a train station",
        "Ways to travel",
        "Things with wings",
        "Things on a map",
        "Famous buildings or landmarks",
        "Things you find in a city",
        "Things you find on a farm",
        "Things you see at the seaside",
        "Places you can swim",
        "Things in space",
        "Planets and moons",
        "Things in a museum",
        // Words and ideas
        "Words that rhyme with cat",
        "Words that rhyme with day",
        "Words that rhyme with light",
        "Words that start with S",
        "Words that start with B",
        "Words with double letters",
        "Words that end in -ing",
        "Things that are big",
        "Things that are tiny",
        "Things that are fast",
        "Things that are slow",
        "Things that smell nice",
        "Things that smell bad",
        "Things that are loud",
        "Things that are quiet",
        "Things that are green",
        "Things that are blue",
        "Things that are white",
        "Things that are orange",
        "Things that are purple",
        "Things you say hello with",
        "Ways to say goodbye",
        "Things that make you laugh",
        "Things that make you sleepy",
        "Things you can count",
        "Numbers bigger than ten",
        "Shapes",
        "Things with numbers on them",
        "Things that have keys",
        "Things with a face",
        // Stories and imagination
        "Fairy tale characters",
        "Magical creatures",
        "Superpowers",
        "Things a pirate has",
        "Things a wizard has",
        "Things in a castle",
        "Things you might find in a treasure chest",
        "Things a robot could do",
        "Dinosaurs",
        "Things that are scary in a fun way",
        "Things in a haunted house",
        "Things an astronaut needs",
        "Things you'd take to a desert island",
        "Holidays and celebrations",
        "Things you do on a rainy day",
        "Things you do on a sunny day",
        "Things that come in a set",
        "Things that are sweet",
        "Things that are sour",
        "Things you can plant",
    )
}
